project_id = "nvrywmshqmiudpvzgxgm"

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.submit-form]
verify_jwt = false

[functions.delete-user-account]
verify_jwt = true

[functions.generate-form]
verify_jwt = false

[auth]
enable_leaked_password_check = true
